# Generated by Django 2.0.2 on 2018-05-19 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180501_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Email',
            new_name='email',
        ),
    ]
